import type { Locale } from "./types";

const EN = {
  title: "POWER BLANK",
  subtitle: "TACTICAL OPERATIONS",
  nick: "CALLSIGN",
  quick: "QUICK MATCH",
  channels: "CHANNELS",
  shop: "ARMORY",
  settings: "SETTINGS",
  back: "BACK",
  play: "ENTER CHANNEL",
  create: "CREATE ROOM",
  join: "JOIN",
  roomLocked: "ROOM LOCKED",
  password: "PASSWORD",
  wrongPass: "WRONG PASSWORD",
  ready: "READY",
  start: "START MATCH",
  unready: "UNREADY",
  swap: "SWITCH TEAM",
  tdm: "TEAM DEATHMATCH",
  demolition: "DEMOLITION",
  elimination: "ELIMINATION",
  clickPlay: "CLICK TO FIGHT",
  clickHint: "WASD move · mouse aim · LMB fire · RMB ads · R reload · SHIFT sprint",
  tapPlay: "TAP TO FIGHT",
  tapHint: "Left thumb: drag to move · right thumb: drag to aim · hold FIRE",
  clickAim: "CLICK TO AIM",
  paused: "PAUSED",
  resume: "RESUME",
  quit: "LEAVE MATCH",
  victory: "VICTORY",
  defeat: "DEFEAT",
  draw: "DRAW",
  continue: "RETURN TO CHANNEL",
  playAgain: "PLAY AGAIN",
  rematch: "REMATCH",
  lastMatch: "LAST",
  cancelLaunch: "CANCEL",
  launchAborted: "LAUNCH ABORTED",
  lockAndLoad: "LOCK AND LOAD",
  vs: "VS",
  mission: "MISSION START",
  killed: "YOU KILLED",
  killedBy: "KILLED BY",
  headshot: "HEADSHOT",
  planted: "BOMB PLANTED",
  defused: "BOMB DEFUSED",
  respawn: "RESPAWN",
  gp: "GP",
  buy: "EQUIP",
  owned: "OWNED",
  equipped: "EQUIPPED",
  locked: "LOCKED",
  sidearm: "SIDEARM",
  lethal: "LETHAL",
  sensitivity: "MOUSE SENSITIVITY",
  invertY: "INVERT Y",
  fov: "FIELD OF VIEW",
  master: "MASTER VOLUME",
  sfx: "SFX",
  music: "MUSIC",
  shake: "SCREEN SHAKE",
  quality: "GRAPHICS",
  language: "LANGUAGE",
  high: "HIGH",
  low: "LOW",
  players: "OPERATORS",
  ping: "PING",
  map: "MAP",
  mode: "MODE",
  room: "ROOM",
  loadout: "LOADOUT",
  primary: "PRIMARY",
  pistol: "SIDEARM",
  nade: "LETHAL",
  score: "SCOREBOARD",
  kda: "K / D / A",
  holdPlant: "HOLD E TO PLANT",
  holdDefuse: "HOLD E TO DEFUSE",
  empty: "NO ROOMS — CREATE ONE",
  online: "ONLINE",
  host: "HOST",
  you: "YOU",
  mvp: "MVP",
  earned: "GP EARNED",
  gpWin: "WIN BONUS",
  gpKillLine: "KILLS",
  gpAssistLine: "ASSISTS",
  gpMvpBonus: "MVP BONUS",
  gpTotal: "TOTAL GP",
  touchFire: "FIRE",
  touchJump: "JUMP",
  touchRel: "REL",
  touchAds: "ADS",
  results: "MATCH RESULTS",
  roundWin: "ROUND WIN",
  lastStand: "LAST MAN STANDING",
  ace: "ACE",
  quad: "QUAD KILL",
  triple: "TRIPLE KILL",
  double: "DOUBLE KILL",
  firstBlood: "FIRST BLOOD",
  enemyDown: "ENEMY DOWN",
  roundLoss: "ROUND LOSS",
  tenSeconds: "10 SECONDS",
  down: "DOWN",
  freezeBuy: "EQUIP",
  armorBuy: "ARMOR",
  shopFree: "FREE",
  shopNeed: "NEED",
  pickBomb: "HOLD E TO PICK UP BOMB",
  ctWin: "CT WIN",
  trWin: "TR WIN",
  matchPoint: "MATCH POINT",
  matchOver: "MATCH OVER",
  kitExt: "EXT",
  kitRd: "RD",
  kitLsr: "LSR",
  firstTo: "FIRST TO 5",
  youBomb: "YOU HAVE THE BOMB",
  goSite: "GO SITE",
  emptySlot: "EMPTY",
  entered: "entered the room",
  isReady: "is ready",
  matchStarting: "MATCH STARTING",
  chatPh: "SAY SOMETHING",
  send: "SEND",
  waiting: "WAITING",
  roomNo: "ROOM",
};

const ID: typeof EN = {
  title: "POWER BLANK",
  subtitle: "OPERASI TAKTIS",
  nick: "NAMA PANGGILAN",
  quick: "MAIN CEPAT",
  channels: "CHANNEL",
  shop: "GUDANG SENJATA",
  settings: "PENGATURAN",
  back: "KEMBALI",
  play: "MASUK CHANNEL",
  create: "BUAT ROOM",
  join: "GABUNG",
  roomLocked: "ROOM TERKUNCI",
  password: "KATA SANDI",
  wrongPass: "SALAH PASSWORD",
  ready: "SIAP",
  start: "MULAI PERTANDINGAN",
  unready: "BATAL SIAP",
  swap: "GANTI TIM",
  tdm: "TEAM DEATHMATCH",
  demolition: "DEMOLISI",
  elimination: "ELIMINASI",
  clickPlay: "KLIK UNTUK BERTARUNG",
  clickHint: "WASD gerak · mouse bidik · LMB tembak · RMB bidik · R isi peluru · SHIFT lari",
  tapPlay: "KETUK UNTUK BERTARUNG",
  tapHint: "Ibu jari kiri: geser untuk gerak · kanan: geser untuk bidik · tahan TEMBAK",
  clickAim: "KETUK UNTUK BIDIK",
  paused: "JEDA",
  resume: "LANJUT",
  quit: "KELUAR",
  victory: "KEMENANGAN",
  defeat: "KALAH",
  draw: "SERI",
  continue: "KEMBALI KE CHANNEL",
  playAgain: "MAIN LAGI",
  rematch: "REMATCH",
  lastMatch: "TERAKHIR",
  cancelLaunch: "BATAL",
  launchAborted: "HITUNG MUNDUR DIBATALKAN",
  lockAndLoad: "KUNCI DAN SIAP",
  vs: "VS",
  mission: "MISI DIMULAI",
  killed: "KAMU MEMBUNUH",
  killedBy: "DIBUNUH OLEH",
  headshot: "TEMBAKAN KEPALA",
  planted: "BOM DIPASANG",
  defused: "BOM DINONAKTIFKAN",
  respawn: "HIDUP KEMBALI",
  gp: "GP",
  buy: "PAKAI",
  owned: "DIMILIKI",
  equipped: "DIPAKAI",
  locked: "TERKUNCI",
  sidearm: "PISTOL",
  lethal: "LETHAL",
  sensitivity: "SENSITIVITAS MOUSE",
  invertY: "BALIK SUMBU Y",
  fov: "SUDUT PANDANG",
  master: "VOLUME UTAMA",
  sfx: "EFEK",
  music: "MUSIK",
  shake: "GOYANG LAYAR",
  quality: "GRAFIS",
  language: "BAHASA",
  high: "TINGGI",
  low: "RENDAH",
  players: "OPERATOR",
  ping: "PING",
  map: "PETA",
  mode: "MODE",
  room: "ROOM",
  loadout: "BEKAL",
  primary: "UTAMA",
  pistol: "PISTOL",
  nade: "GRANAT",
  score: "PAPAN SKOR",
  kda: "K / D / A",
  holdPlant: "TAHAN E UNTUK PASANG",
  holdDefuse: "TAHAN E UNTUK CABUT",
  empty: "TIDAK ADA ROOM — BUAT BARU",
  online: "ONLINE",
  host: "HOST",
  you: "KAMU",
  mvp: "MVP",
  earned: "GP DIDAPAT",
  gpWin: "BONUS MENANG",
  gpKillLine: "KILL",
  gpAssistLine: "ASSIST",
  gpMvpBonus: "BONUS MVP",
  gpTotal: "TOTAL GP",
  touchFire: "TEMBAK",
  touchJump: "LONCAT",
  touchRel: "ISI",
  touchAds: "BIDIK",
  results: "HASIL PERTANDINGAN",
  roundWin: "MENANG RONDE",
  lastStand: "TERAKHIR BERTAHAN",
  ace: "ACE",
  quad: "QUAD KILL",
  triple: "TRIPLE KILL",
  double: "DOUBLE KILL",
  firstBlood: "FIRST BLOOD",
  enemyDown: "MUSUH DOWN",
  roundLoss: "KALAH RONDE",
  tenSeconds: "10 DETIK",
  down: "GUGUR",
  freezeBuy: "LENGKAPI",
  armorBuy: "ARMOR",
  shopFree: "GRATIS",
  shopNeed: "KURANG",
  pickBomb: "TAHAN E UNTUK AMBIL BOM",
  ctWin: "CT MENANG",
  trWin: "TR MENANG",
  matchPoint: "MATCH POINT",
  matchOver: "PERTANDINGAN SELESAI",
  kitExt: "EXT",
  kitRd: "RD",
  kitLsr: "LSR",
  firstTo: "PERTAMA KE 5",
  youBomb: "KAMU BAWA BOM",
  goSite: "MENUJU SITE",
  emptySlot: "KOSONG",
  entered: "masuk room",
  isReady: "siap",
  matchStarting: "PERTANDINGAN DIMULAI",
  chatPh: "KETIK PESAN",
  send: "KIRIM",
  waiting: "MENUNGGU",
  roomNo: "ROOM",
};

export const STR: Record<Locale, typeof EN> = { en: EN, id: ID };

export const MAP_META: Record<
  string,
  { name: string; nameId: string; blurb: string; blurbId: string; splash: string }
> = {
  depot: {
    name: "DEPOT",
    nameId: "DEPOT",
    blurb: "Indoor warehouse. Tight mid, catwalks, crate mazes.",
    blurbId: "Gudang indoor. Mid rapat, catwalk, labirin peti.",
    splash: "/game/container.jpg",
  },
  harbor: {
    name: "HARBOR",
    nameId: "PELABUHAN",
    blurb: "Container yard at dusk. Long angles, stacked cover.",
    blurbId: "Lapangan kontainer senja. Sudut panjang, cover bertingkat.",
    splash: "/game/sand.jpg",
  },
  bazaar: {
    name: "BAZAAR",
    nameId: "PASAR",
    blurb: "Night market alleys. Close quarters, rooftops, stalls.",
    blurbId: "Lorong pasar malam. Jarak dekat, atap, kios.",
    splash: "/game/brick.jpg",
  },
};

export const BOT_NAMES = [
  "REX",
  "SHADOW",
  "VIPER",
  "KADE",
  "NOVA",
  "HELIX",
  "GHOST",
  "SABLE",
  "DIKA",
  "PUTRA",
  "ARIEF",
  "RAKA",
  "AGUS",
  "NINJA",
  "BLITZ",
  "ONYX",
  "FALCON",
  "RAZOR",
  "KIRA",
  "ZERO",
];

export const LOBBY_BANTER: Record<Locale, string[]> = {
  en: ["gl hf", "rush B", "who C4", "go A", "eco this", "ready up", "mid peek", "nice", "lag?", "bomb A"],
  id: ["gl hf", "rush B", "siapa C4", "gas A", "eco dulu", "ready", "peek mid", "bagus", "lag?", "bom A"],
};

